// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKA0EnuyRNpubn97V8yqtY70zDeq2JdlI',
    appId: '1:862424373821:web:fb63c06f19c5a0aea26854',
    messagingSenderId: '862424373821',
    projectId: 'fluttershare-84173',
    authDomain: 'fluttershare-84173.firebaseapp.com',
    databaseURL: 'https://fluttershare-84173-default-rtdb.firebaseio.com',
    storageBucket: 'fluttershare-84173.appspot.com',
    measurementId: 'G-09Z85FK7ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRkRMxstTtoAjuv17DA1CsLuKu23MzMLY',
    appId: '1:862424373821:android:40774cb0e3face76a26854',
    messagingSenderId: '862424373821',
    projectId: 'fluttershare-84173',
    databaseURL: 'https://fluttershare-84173-default-rtdb.firebaseio.com',
    storageBucket: 'fluttershare-84173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl4X9LP859lzrqKcFMKy5uz2HJDvUuCZE',
    appId: '1:862424373821:ios:ba4377cae2e4c2b9a26854',
    messagingSenderId: '862424373821',
    projectId: 'fluttershare-84173',
    databaseURL: 'https://fluttershare-84173-default-rtdb.firebaseio.com',
    storageBucket: 'fluttershare-84173.appspot.com',
    androidClientId: '862424373821-kit8jb18elqgv4ra8ffdii7vrnldiuer.apps.googleusercontent.com',
    iosClientId: '862424373821-14io2q09ds0adbrtgstjv6g4cl6p5s7p.apps.googleusercontent.com',
    iosBundleId: 'com.hotcodes.fluttershare',
  );
}
